<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Fakturenn.ArchitectureTests</RootNamespace>
    <IsPackable>false</IsPackable>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AwesomeAssertions" />
    <PackageReference Include="TngTech.ArchUnitNET.xUnitV3" />
    <PackageReference Include="xunit.v3.mtp-v2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Fakturenn.SharedKernel\Fakturenn.SharedKernel.csproj" />
    <ProjectReference Include="..\..\src\Fakturenn.Infrastructure.Storage\Fakturenn.Infrastructure.Storage.csproj" />
    <ProjectReference Include="..\..\src\Fakturenn.Modules.Invoices\Fakturenn.Modules.Invoices.csproj" />
    <ProjectReference Include="..\..\src\Fakturenn.Modules.Invoices.Contracts\Fakturenn.Modules.Invoices.Contracts.csproj" />
    <ProjectReference Include="..\..\src\Fakturenn.Web\Fakturenn.Web.csproj" />
    <ProjectReference Include="..\..\src\Fakturenn.Modules.Identity\Fakturenn.Modules.Identity.csproj" />
    <ProjectReference Include="..\..\src\Fakturenn.Modules.Identity.Contracts\Fakturenn.Modules.Identity.Contracts.csproj" />
  </ItemGroup>

</Project>
